version: "2.1"
services:
  flink-job-server:
    image: flink-job-server:2.7.0-fixed
    depends_on:
      - jobmanager
    volumes:
     - beam-artifacts-staging-volume:/tmp/beam-artifact-staging # current limitation: job-server needs to have access to artifact staging area as taskmanagers
    network_mode: "host"  # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    command:  ["--flink-master-url=localhost:8081", ]
  jobmanager:
    image: flink:1.5.3-scala_2.11
    command: jobmanager
    network_mode: "host" # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    environment:
    - JOB_MANAGER_RPC_ADDRESS=localhost
  taskmanager:
    image: flink-with-docker:1.5.3-scala_2.11
    network_mode: "host"  # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    depends_on:
    - jobmanager
    command: taskmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # needs access to docker-socket of host machine
      - beam-artifacts-staging-volume:/tmp/beam-artifact-staging # current limitation: job-server needs to have access to artifact staging area as taskmanagers
volumes:
   beam-artifacts-staging-volume: