version: "2.2"
services:
#  flink-job-server:
#    image: apache/beam_flink1.10_job_server:latest
#    user: "1000:1000"
#    depends_on:
#      - jobmanager
#    volumes:
#      - beam-artifacts-staging-volume:/tmp/beam-artifact-staging
#    network_mode: "host"  # need use host networking for the SDK harness container to reach to taskmanager under localhost
#    command:  ["--flink-master=localhost:8081", "--artifacts-dir=/tmp/beam-artifact-staging" ]
  jobmanager:
    #    image: flink:1.10.0-scala_2.11
    build: .
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    network_mode: "host" # need use host networking for the SDK harness container to reach to taskmanager under localhost
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
        jobmanager.memory.jvm-metaspace.size: 1024m
  taskmanager:
#    image: flink:1.10.0-scala_2.11
    build: .
    user: "1000:1000"
    network_mode: "host"  # need use host networking for the SDK harness container to reach to taskmanager under localhost
    depends_on:
    - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
        taskmanager.numberOfTaskSlots: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # needs access to docker-socket of host machine
      - beam-artifacts-staging-volume:/tmp/beam-artifact-staging
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    network_mode: "host"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    network_mode: "host"
    environment:
      KAFKA_ADVERTISED_LISTENERS: ONLY://:9092
      KAFKA_LISTENERS: ONLY://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ONLY:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: ONLY
      KAFKA_CREATE_TOPICS: "beam-input:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
volumes:
   beam-artifacts-staging-volume:
